name: Build Software
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Clean Install
        run: npm install --force
      - name: Build Web
        run: npm run build
      - name: Build EXE
        run: npx electron-builder --win --portable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: Business-Software-EXE
          path: dist_electron/*.exe
