name: Build Desktop Software
on: [push]

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Version 3 ko 4 kar diya

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Version 3 ko 4 kar diya
        with:
          node-version: 20 # 18 ko 20 kar diya taake latest rahe

      - name: Install Dependencies
        run: npm install

      - name: Build Web Project
        run: npm run build

      - name: Build Electron EXE
        run: npx electron-builder --win --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Software
        uses: actions/upload-artifact@v4 # Version 3 ko 4 kar diya
        with:
          name: Business-App-EXE
          path: dist/*.exe

